spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/curso
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: tul2023
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled : true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8080